name: lint

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  eslint:
    name: Lint TypeScript/JavaScript
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Set up Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: 16
          check-latest: true
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci --no-audit

      - name: Run eslint
        run: npm run lint

  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Set up problem matcher
        uses: xt0rted/markdownlint-problem-matcher@98d94724052d20ca2e06c091f202e4c66c3c59fb # tag=v2.0.0
      - name: Run markdownlint
        run: npx --package markdownlint-cli markdownlint '**/*.md' --ignore node_modules
